# Site Settings
title: Indranil's home 
# tagline: Indranil's home
email: indranilm256@gmail.com
description: >
  My personal website for blog
#baseurl: "/bulma-clean-theme"
url: "http://indranilm256.github.io"
permalink: pretty
favicon: /favicon1.png
#gh_sponsor: chrisrhymes
hide_share_buttons: false

paginate: 5
paginate_path: "/blog/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortnames
  shortname: indranilm256-github-io


plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown
  - rouge

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

#google_analytics: UA-code-here

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: false
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Indranil Mandal"
      layout: post
      image: https://via.placeholder.com/1200x800
      show_sidebar: false

markdown: kramdown
highlighter: rouge

footer_menu: example_footer_menu

feed:
  tags: 
    only: 
      -

# collections:
#   products: 
#     output: true
#     layout: product
#     image: https://via.placeholder.com/800x600
#     show_sidebar: false